server: 
  port: 8100

spring: 
  jpa: 
    show-sql: true
  h2:
    console:
      enabled: true
  cloud:
    loadbalancer:
      ribbon:
        enabled: true

currency-exchange-service:
  ribbon:
    listOfServers: localhost:8070, localhost:8060